spring:
  application:
    name: dynamic-batch

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

batch:
  meta:
    datasource:
      jdbc-url: jdbc:postgresql://localhost:5432/pts?currentSchema=batch
      username: postgres
      password: 12341234
      driver-class-name: org.postgresql.Driver

  source:
    datasource:
      jdbc-url: jdbc:mysql://localhost:3306/batch
      username: root
      password: 12341234
      driver-class-name: com.mysql.cj.jdbc.Driver

  target:
    datasource:
      jdbc-url: jdbc:postgresql://localhost:5432/pts?currentSchema=batch
      username: postgres
      password: 12341234
      driver-class-name: org.postgresql.Driver